pub mod error;
pub mod object_id;
pub mod object_status;
pub mod quality;
pub mod models;
pub mod manager;
pub mod merge;
pub mod source;
pub mod favor;
pub mod migration;

pub use error::MusicLibraryError;
pub use object_id::ObjectId;
pub use object_status::ObjectStatus;
pub use quality::Quality;
pub use models::music_object::{MusicObject, ObjectKind};
pub use models::trace_link::TraceLink;
pub use models::master_song::MasterSong;
pub use models::master_album::MasterAlbum;
pub use models::master_artist::MasterArtist;
pub use models::source_song::{SourceSong, SourceSongDetails};
pub use models::source_album::{SourceAlbum, SourceAlbumDetails};
pub use models::source_artist::{SourceArtist, SourceArtistDetails};
pub use models::song_full::{SongFull, AlbumFull, ArtistFull};
pub use manager::MusicStorageSourceLibraryManager;
